export const ERP_ROLE_KEYS = [
  'ADMIN',
  'BOARD_OWNER',
  'CEO_MANAGING_DIRECTOR',
  'CTO',
  'COO',
  'DEPARTMENT_HEAD',
  'ENGINEERING_HEAD',
  'DESIGN_HEAD',
  'PROJECT_MANAGEMENT_HEAD',
  'PRODUCT_HEAD',
  'HR_HEAD',
  'FINANCE_HEAD',
  'SALES_MARKETING_HEAD',
  'SUPPORT_OPERATIONS_HEAD',
  'TECH_LEAD',
  'QA_LEAD',
  'DEVOPS_ENGINEER',
  'PRODUCT_MANAGER',
  'PROJECT_MANAGER',
  'SENIOR_DEVELOPER',
  'SCRUM_MASTER',
  'HR_MANAGER',
  'SALES_MANAGER',
  'MID_LEVEL_DEVELOPER',
  'UI_UX_DESIGNER',
  'ACCOUNTANT',
  'BUSINESS_DEVELOPMENT_EXECUTIVE',
  'QA_ENGINEER',
  'PAYROLL_OFFICER',
  'JUNIOR_DEVELOPER',
  'GRAPHIC_DESIGNER',
  'HR_EXECUTIVE',
  'MARKETING_EXECUTIVE',
  'OFFICE_ADMIN',
  'IT_SUPPORT',
  'INTERN',
  'CLIENT',
]

// Scoring system to be followed
export const ERP_ROLES = [
  { key: 'ADMIN', score: 100 },
  { key: 'BOARD_OWNER', score: 100 },
  { key: 'CEO_MANAGING_DIRECTOR', score: 95 },
  { key: 'CTO', score: 90 },
  { key: 'COO', score: 88 },
  { key: 'DEPARTMENT_HEAD', score: 85 },
  { key: 'ENGINEERING_HEAD', score: 84 },
  { key: 'DESIGN_HEAD', score: 83 },
  { key: 'PROJECT_MANAGEMENT_HEAD', score: 82 },
  { key: 'PRODUCT_HEAD', score: 81 },
  { key: 'HR_HEAD', score: 80 },
  { key: 'FINANCE_HEAD', score: 79 },
  { key: 'SALES_MARKETING_HEAD', score: 78 },
  { key: 'SUPPORT_OPERATIONS_HEAD', score: 77 },
  { key: 'TECH_LEAD', score: 75 },
  { key: 'QA_LEAD', score: 74 },
  { key: 'DEVOPS_ENGINEER', score: 73 },
  { key: 'PRODUCT_MANAGER', score: 73 },
  { key: 'PROJECT_MANAGER', score: 72 },
  { key: 'SENIOR_DEVELOPER', score: 70 },
  { key: 'SCRUM_MASTER', score: 70 },
  { key: 'HR_MANAGER', score: 70 },
  { key: 'SALES_MANAGER', score: 70 },
  { key: 'MID_LEVEL_DEVELOPER', score: 65 },
  { key: 'UI_UX_DESIGNER', score: 65 },
  { key: 'ACCOUNTANT', score: 65 },
  { key: 'BUSINESS_DEVELOPMENT_EXECUTIVE', score: 65 },
  { key: 'QA_ENGINEER', score: 62 },
  { key: 'PAYROLL_OFFICER', score: 63 },
  { key: 'JUNIOR_DEVELOPER', score: 60 },
  { key: 'GRAPHIC_DESIGNER', score: 60 },
  { key: 'HR_EXECUTIVE', score: 60 },
  { key: 'MARKETING_EXECUTIVE', score: 60 },
  { key: 'OFFICE_ADMIN', score: 58 },
  { key: 'IT_SUPPORT', score: 55 },
  { key: 'INTERN', score: 40 },
  { key: 'CLIENT', score: 10 },
]
